### ISSUE TITLE
Incorrect dropdown content positioning for render-in-place

### ISSUE THREAD

**Issue by artursmirnov** [cibernox/ember-power-select-with-create#65] opened 2017-05-01 12:37 UTC
Updating to latest (`0.4.3`) version from `0.3.1` I faced the issue. Dropdown content is getting shifted from trigger as if it was rendered  in wormhole.

![image](https://cloud.githubusercontent.com/assets/4066489/25579746/3c8a0882-2e83-11e7-8848-229501e48061.png)

Also in devtools I can see 

![image](https://cloud.githubusercontent.com/assets/4066489/25579781/7736e112-2e83-11e7-826f-6deb14f6532f.png)

And when I disable those styles

![image](https://cloud.githubusercontent.com/assets/4066489/25579792/9c246d14-2e83-11e7-8028-a172354fc57d.png)

the dropdown gets back to where it supposed be

![image](https://cloud.githubusercontent.com/assets/4066489/25579799/b66635d6-2e83-11e7-8cc4-dfd05cf6970b.png)

The issue only appears for `renderInPlace=true`. Otherwise it works as expected.

**Comment by cibernox** [comment] 2017-05-02 16:44
I believe that this was fixed by https://github.com/cibernox/ember-basic-dropdown/pull/291.

Can you ensure you update ember-basic-dropdown (which is used by ember-power-select) and this works? I'm going to close it since I'm 99% this was the cause, but open if it's not.

**Closed by cibernox** 2017-05-02 16:44 UTC

**Comment by artursmirnov** [comment] 2017-05-03 09:35
@cibernox yep, that was happening because yarn kept old versions for nested dependencies. Cleaning up node modules and rebuilding yarn.lock solved an issue. Thanks!
