### ISSUE TITLE
Multi select:  search text not being reset after creating new option from buildSuggestion

### ISSUE THREAD

**Issue by hotterd** [cibernox/ember-power-select-with-create#11] opened 2016-02-29 23:32 UTC
I'm using a basic setup with power-select-with-create like this:

```
              {{#power-select-with-create
                    multiple=true
                    options=allTags
                    selected=selectedTag
                    onchange=(action (mut formTag))
                    oncreate=(action "createTag")
                    closeOnSelect=false
                    buildSuggestion=buildSuggestion
                    as |name|
                  }}
                    {{name}}
              {{/power-select-with-create}}
```
It appears to me that after a new option is created, the searchText is not going away. Is this the intended behavior?

**Comment by cibernox** [comment] 2016-03-01 00:07
Probaly not, but I won't have time this week to check it. @felixkiss Are you aware of this?

@hotterd Version of Ember Power Select in use?

**Comment by hotterd** [comment] 2016-03-01 00:19
@cibernox I'm using the latest version:

```
    "ember-power-select": "^0.9.0-beta.6",
    "ember-power-select-with-create": "0.1.5",
```

Also tried stable release 0.8.6

**Comment by cibernox** [comment] 2016-03-01 00:29
As a side note, this addon is in my account but I don't personally use it in my projects. But I'd bet that it's not intended behaviour.

**Comment by felixkiss** [comment] 2016-03-02 18:22
I can look into it over the weekend

**Comment by felixkiss** [comment] 2016-04-12 15:34
@hotterd Sorry for not responding for so long.

I tried to write a failing test that reproduces your described environment, but it works.

Here is the test:
```js
test('it resets searchText after creating a new item', function(assert) {
  this.set('countries', [{name: 'Canada'}]);
  this.set('selectedCountry', null);
  this.on('createCountry', (country) => {
    this.get('countries').push({name: country});
  });

  this.render(hbs`
    {{#power-select-with-create
        multiple=true
        options=countries
        selected=selectedCountry
        onchange=(action (mut selectedCountry))
        oncreate=(action "createCountry")
        closeOnSelect=false
        buildSuggestion=buildSuggestion
        as |country|
    }}
      {{country.name}}
    {{/power-select-with-create}}
  `);

  clickTrigger();
  Ember.run(() => typeInSearch('Foo Bar'));
  nativeMouseUp('.ember-power-select-option:eq(0)');

  clickTrigger();

  Ember.run(() => assert.equal(
    this.$('.ember-power-select-trigger-multiple-input').val(),
    '',
    'search field should be cleared'
  ));
});
```

Are you still having this problem?

**Comment by felixkiss** [comment] 2016-04-12 17:52
Ok, I got my failing test now. This needs to be addressed in ember-power-select. I have opened an issue there (cibernox/ember-power-select#450).

**Comment by felixkiss** [comment] 2016-04-12 18:38
@cibernox says it is intended behavior in ember-power-select, and I don't want to go too far down a different path, because users will expect this to behave exactly like EPS + an option to create new entries. 

But if you want you select to behave differently, clear it manually in the `onchange` action ([as suggested here](https://github.com/cibernox/ember-power-select/issues/450#issuecomment-209039602)):

```js
actions: {
  changeTags(tags, select) {
    this.set('selectedTags', tags);
    select.actions.search(''); // search an empty string.
  }
}
```

**Closed by felixkiss** 2016-04-12 18:38 UTC

**Comment by cibernox** [comment] 2016-04-12 18:45
@felixkiss @hotterd I'd say that is perfectly fine for **this addon** (not EPS) to clear the search after the creation of a new option. 

Seems the expected behaviour to me.

Maybe `power-select-with-create` can call `select.actions.search('')` in the `oncreate` action automatically?

**Comment by felixkiss** [comment] 2016-04-12 18:51
It could. Does this have any side effects, when using an expensive custom search (e.g. request to search Github API)?

But then again, what if you don't want that behavior? You can't really undo the call. IMO selecting multiple options from one search result is as plausible here as in EPS.

I would prefer for to be implemented specifically by the user. Especially, because it ist just a single line of code.

**Comment by cibernox** [comment] 2016-04-12 19:11
No, invoking `select.actions.search` with an empty string is (intentionally) a fast path. It won't even invoke the `search` action, it just resets the component to the initial options and clears the input.

I agree that **select** a value should not clear the search by default, but _maybe_ **create** a new option should. Just throwing the idea.

**Comment by hotterd** [comment] 2016-05-12 03:09
Thanks @felixkiss @cibernox . Sorry for late reply.
I am now trying to clear the search text manually after option is created as proposed above. However, it doesn't seem to work for me:

```
    didSelect(tags, select) {
      Ember.Logger.debug(`selected with ${tags} and ${select}`);
      this.set('value', tags);
      select.actions.search('');
    }
```
this hook only fired when I select an already existed option, and it seems the second 'select' parameter is undefined. It's not fired when I create a new option.

Then I tried to do similar in create action, it also does not accept second parameter.

I'm using ` "ember-power-select": "0.10.4"`, and `"ember-power-select-with-create": "0.1.10"`

BTW, I agree with @cibernox that in the scenario when a new option is created on the fly, the search text used to create the option should be cleared by default. There seems to have no benefit to retain the text in this situation.
